version: '2.1'
services:
  dns:
    image: andyshinn/dnsmasq:2.76
    cap_add:
     - NET_ADMIN
    restart: unless-stopped
    logging:
      driver: "journald"
    ports:
     - "${LISTEN_ADDR}:53:53/udp"
    #network_mode: "host"
    volumes:
     - ./hostsdata:/hostsdata
    command: --log-facility=- --log-queries --dns-loop-detect --no-dhcp-interface=eth0 --no-hosts --hostsdir=/hostsdata
